# JIRA Configuration File Example
# Copy this file to .jira.config.yaml and fill in your details
# This file should be added to .gitignore for security

jira:
  # Your JIRA server URL
  # Examples:
  #   - Cloud: https://your-domain.atlassian.net
  #   - On-premise: https://jiradc.ext.net.nokia.com
  url: "https://jiradc.ext.net.nokia.com"

  # JIRA Personal Access Token (PAT)
  # This uses Bearer token authentication (not Basic Auth)
  #
  # How to generate a PAT:
  #   1. Log into your JIRA instance
  #   2. Go to Profile → Personal Access Tokens
  #   3. Create a new token with appropriate permissions
  #   4. Copy the token and paste it below
  #
  # Reference: https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html
  api_token: "your-personal-access-token-here"

# Optional: Field mappings for custom JIRA fields
# Uncomment and adjust based on your JIRA instance
# field_mappings:
#   target_start_date: "customfield_10015"
#   target_end_date: "customfield_10016"
